### ISSUE TITLE
When doing red apple test.

### ISSUE THREAD

**Issue by vrotmelk** [rbbrdckybk/ai-art-generator#15]
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips\vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Restored from checkpoints/vqgan_imagenet_f16_16384.ckpt
Using device: cuda:0
Optimising using: Adam
Using text prompts: ['a red apple']
Using seed: 16544599355900
i: 0, loss: 0.913828, losses: 0.913828
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "C:\Users\mikeb\ai-art-generator\vqgan.py", line 867, in <module>
    train(i)
  File "C:\Users\mikeb\ai-art-generator\vqgan.py", line 751, in train
    checkin(i, lossAll)
  File "C:\Users\mikeb\anaconda3\envs\ai-art\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mikeb\ai-art-generator\vqgan.py", line 721, in checkin
    TF.to_pil_image(out[0].cpu()).save(args.output, pnginfo=info)
  File "C:\Users\mikeb\anaconda3\envs\ai-art\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'output/output.png'

**Comment by plactoid** [comment]
You may have to create a folder in that directory for the output and name it output, it doesn't seem to consistently generate the folder on first run.

**Comment by rbbrdckybk** [comment]
Added a check for subdirs that don't exist in the output folder; this should work properly now - thanks!
