### ISSUE TITLE
Error while running the test command

### ISSUE THREAD

**Issue by 0xinit** [rbbrdckybk/ai-art-generator#2]
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Restored from checkpoints/vqgan_imagenet_f16_16384.ckpt
Using device: cuda:0
Optimising using: Adam
Using text prompts: ['a red apple']
Using seed: 1260714667749887246
i: 0, loss: 0.906549, losses: 0.906549
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/gaurav/Desktop/ai_art_generators/ai-art-generator/vqgan.py", line 867, in <module>
    train(i)
  File "/home/gaurav/Desktop/ai_art_generators/ai-art-generator/vqgan.py", line 751, in train
    checkin(i, lossAll)
  File "/home/gaurav/anaconda3/envs/ai-art/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/gaurav/Desktop/ai_art_generators/ai-art-generator/vqgan.py", line 721, in checkin
    TF.to_pil_image(out[0].cpu()).save(args.output, pnginfo=info)
  File "/home/gaurav/anaconda3/envs/ai-art/lib/python3.9/site-packages/PIL/Image.py", line 2209, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'output/output.png'

**Comment by 0xinit** [comment]
This is the error that i am currently getting when I run "python vqgan.py -s 128 128 -i 200 -p "a red apple" -o output/output.png" 
I am not sure why, but I think this has to do something with PIL version? 

Let me know if you know of any solutions. Thanks!

**Comment by 0xinit** [comment]
resolved it. Some dependency issue.
