### ISSUE TITLE
Diffusion _pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by alialshamali** [rbbrdckybk/ai-art-generator#5]
I am getting the following error while running diffusion.py
```
 Traceback (most recent call last):
  File "/home/ali/Desktop/ai-art-generator/diffusion.py", line 1650, in <module>
    secondary_model.load_state_dict(torch.load(f'{model_path}/secondary_model_imagenet_2.pth', map_location='cpu'))
  File "/home/ali/miniconda3/envs/ai-art/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ali/miniconda3/envs/ai-art/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```
The command I am running is
```
python diffusion.py -s 400 400 -i 250 -p "a shining lighthouse on the shore of a tropical island in a raging storm" -o output/diff.png
```

Thank you

**Comment by alialshamali** [comment]
Troubleshooted the problem its appears one the links are broken for `secondary_model_imagenet_2.pth` instructions need to be updated to reflect the changes. I download from a [new source](https://ipfs.pollinations.ai/ipfs/bafybeibaawhhk7fhyhvmm7x24zwwkeuocuizbqbcg5nqx64jq42j75rdiy/secondary_model_imagenet_2.pth) the required model.

**Comment by rbbrdckybk** [comment]
Thanks - updated the readme with your working link!
